# Generated by Django 3.1.3 on 2020-11-19 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='savedrecipes',
            constraint=models.UniqueConstraint(fields=('recipe_id', 'user'), name='unique_saved'),
        ),
    ]
