# Generated by Django 3.1.3 on 2020-11-19 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0002_auto_20201119_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedrecipes',
            name='recipe_id',
            field=models.CharField(max_length=10),
        ),
    ]
