# Generated by Django 3.1.3 on 2020-11-21 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0003_auto_20201119_0332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grocerylistitem',
            old_name='ammount',
            new_name='amount',
        ),
    ]
