# Generated by Django 3.1.3 on 2020-11-21 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0005_auto_20201121_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerylistitem',
            name='ingredient_id',
            field=models.FloatField(),
        ),
    ]
