# Generated by Django 3.1.3 on 2020-11-21 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0006_auto_20201121_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerylistitem',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='grocerylistitem',
            name='ingredient_id',
            field=models.IntegerField(),
        ),
    ]
