# Generated by Django 3.1.3 on 2020-11-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0007_auto_20201121_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocerylistitem',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
    ]
